// <auto-generated />
using System;
using CondominioDev.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CondominioDev.Migrations
{
    [DbContext(typeof(DevCondominioContext))]
    [Migration("20220918024753_DespesasAddNullableHabitanteIdReceitasAddNullableHabitanteIdHabitanteAddNullableDataNascimento")]
    partial class DespesasAddNullableHabitanteIdReceitasAddNullableHabitanteIdHabitanteAddNullableDataNascimento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CondominioDev.Models.Despesas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HabitanteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("HabitanteId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("CondominioDev.Models.Habitante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("Date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Renda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("Habitantes");
                });

            modelBuilder.Entity("CondominioDev.Models.Receitas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HabitanteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("HabitanteId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("CondominioDev.Models.Despesas", b =>
                {
                    b.HasOne("CondominioDev.Models.Habitante", "Habitante")
                        .WithMany()
                        .HasForeignKey("HabitanteId");

                    b.Navigation("Habitante");
                });

            modelBuilder.Entity("CondominioDev.Models.Receitas", b =>
                {
                    b.HasOne("CondominioDev.Models.Habitante", "Habitante")
                        .WithMany()
                        .HasForeignKey("HabitanteId");

                    b.Navigation("Habitante");
                });
#pragma warning restore 612, 618
        }
    }
}
